AppBundle\Entity\Comment:
    type: entity
    table: `comment`
    repositoryClass: AppBundle\Entity\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hashId:
            type: string
            length: '32'
        created:
            type: datetime
        dateCreated:
            type: date
        read:
            column: `read`
            type: boolean
        text:
            type: text
        vote:
            type: integer

    uniqueConstraints:
        hashId:
          columns: hashId

    indexes:
        created:
            columns: created
        dateCreated:
            columns: dateCreated
        isRead:
            columns: read
        vote:
            columns: vote

    oneToMany:
        children:
            targetEntity: Comment
            mappedBy: parent
        votes:
            targetEntity: VoteComment
            mappedBy: comment
    
    manyToOne:
        parent:
            targetEntity: Comment
            inversedBy: children
            joinColumn:
                name: parentId
                referencedColumnName: id

        parentUser:
            targetEntity: User
            joinColumn:
                name: parentUserId
                referencedColumnName: id
        
        post:
            targetEntity: Post
            inversedBy: comments
            joinColumn:
                name: postId
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: comments
            joinColumn:
                name: userId
                referencedColumnName: id

    lifecycleCallbacks: {  }
