AppBundle\Entity\Post:
    type: entity
    table: `post`
    repositoryClass: AppBundle\Entity\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        hashId:
            type: string
            length: '32'
        created:
            column: `created`
            type: datetime
        dateCreated:
            column: `dateCreated`
            type: date
        title:
            column: `title`
            type: string
            length: '255'
        text:
            column: `text`
            type: text
        vote:
            column: `vote`
            type: integer
        commentsCount:
            column: `commentsCount`
            type: integer
            unsigned: true

    uniqueConstraints:
        hashId:
            columns: hashId

    indexes:
        created:
            columns: created
        dateCreated:
            columns: dateCreated
        vote:
            columns: vote

    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: post
        votes:
            targetEntity: VotePost
            mappedBy: post

    manyToOne:
        user:
            targetEntity: User
            inversedBy: posts
            joinColumn:
                name: userId
                referencedColumnName: id
        community:
            targetEntity: Community
            inversedBy: posts
            joinColumn:
                name: communityId
                referencedColumnName: id

    lifecycleCallbacks: {  }
