# freepost
# http://freepo.st
#
# Copyright © 2014-2015 zPlus
# 
# This file is part of freepost.
# freepost is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# freepost is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with freepost. If not, see <http://www.gnu.org/licenses/>.

AppBundle\Entity\User:
    type: entity
    table: `user`
    repositoryClass: AppBundle\Entity\UserRepository
    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    
    fields:
        hashId:
            type: string
            length: '32'
        email:
            column: `email`
            length: '255'
            nullable: true
            type: string
        username:
            column: `username`
            type: string
            length: 255
        password:
            column: `password`
            type: string
            length: 255
        salt:
            column: `salt`
            type: string
            length: '64'
        registered:
            column: `registered`
            type: datetime
        resetPasswordSecretToken:
            type: string
            length: '32'
        isActive:
            type: boolean
    
    uniqueConstraints:
        hashId:
            columns: hashId
        email:
            columns: email
        username:
            columns: username
    
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: user
        posts:
            targetEntity: Post
            mappedBy: user
        commentVotes:
            targetEntity: VoteComment
            mappedBy: user
        postVotes:
            targetEntity: VotePost
            mappedBy: user

    manyToMany:
        communities:
            targetEntity: Community
            inversedBy: users
            joinTable:
                name: users_communities
                joinColumns:
                    userId:
                        referencedColumnName: id
                inverseJoinColumns:
                    communityId:
                        referencedColumnName: id
            
    lifecycleCallbacks: {  }

    
    
    
    