<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends EntityRepository
{
    public function search($communityName)
    {
        $em = $this->getEntityManager();

        return $em->createQuery(
            'SELECT c
            FROM AppBundle:Community c
            WHERE c.name LIKE :communityName
            ORDER BY c.name'
        )
        ->setMaxResults(10)
        ->setParameter('communityName', '%' . $communityName . '%')
        ->getResult();
    }
    
    public function create($communityName, $user)
    {
        // Allow new community only if $user is logged in
        if (is_null($user))
            return NULL;
        
        $em = $this->getEntityManager();
        $datetime = new \DateTime();

        $c = new Community();
        $c->setName($communityName);
        
        // Add the user to this community members
        $user->addCommunity($c);

        $em->persist($c);
        $em->persist($user);

        $em->flush();
        
        return $c;
    }
}
